apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
    tier: database
spec:
  containers:
  - name: api
    image: mma44331/apploction:latest
    ports:
    - containerPort: 8000
    env:
    - name: DB_HOST
      value: "mongodb-service"
    - name: DB_PORT
      value: "27017"
    - name: DB_NAME
      value: "contactsdb"
    - name: DB_COLACTION
      value: "contact"